apiVersion: v1
kind: ConfigMap
metadata:
  name: echry-config
  namespace: echry
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/echry"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://ech-ry.com/api"
  NEXTAUTH_URL: "https://ech-ry.com/"
  NEXTAUTH_SECRET: "rlbFNT/F/HQDBvqO/MBRRkImZQDXpOLhmcJ7jbrwUGs="
  JWT_SECRET: "35ba767220f8821fc56a5e5129dd4aefbbb66c73d1d9edfc72c94ed02e60b32f"
