apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: echry
type: Opaque
data:
  # MongoDB
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy9lY2hyeQ==

  # NextAuth
  NEXTAUTH_SECRET: cmxiRk5UL0YvSFFEQnZxTy9NQlJSa0ltWlFEWHBPTEhtY0o3amJyd1VHcz0=
  NEXTAUTH_URL: aHR0cHM6Ly93d3cuZWNoLXJ5LmNvbQ==

  # JWT
  JWT_SECRET: MzViYTc2NzIyMGY4ODIxZmM1NmE1ZTUxMjlkZDRhZWZiYmI2NmM3M2QxZDllZGZjNzJjOTRlZDAyZTYwYjMyZg==

  # Public API
  NEXT_PUBLIC_API_URL: aHR0cHM6Ly93d3cuZWNoLXJ5LmNvbS9hcGk=

  NEXT_PUBLIC_COGNITO_DOMAIN: aHR0cHM6Ly9hdXRoLmVjaC1yeS5jb20=
  NEXT_PUBLIC_COGNITO_CLIENT_ID: NTltdGFva2F0dTlpOGQzc21rdWVjNG04aWo=
  NEXT_PUBLIC_COGNITO_REDIRECT_URI: aHR0cHM6Ly93d3cuZWNoLXJ5LmNvbQ==
  NEXT_PUBLIC_COGNITO_LOGOUT_URI: aHR0cHM6Ly93d3cuZWNoLXJ5LmNvbQ==
  NEXT_PUBLIC_COGNITO_SCOPES: b3BlbmlkIGVtYWlsIHByb2ZpbGU=
