# ------------ BASE IMAGE -----------------
FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++

# Copie uniquement les fichiers de dépendances
COPY package*.json tsconfig.json ./

# Installation des dépendances avec npm ci
RUN npm ci --legacy-peer-deps
RUN npm install --save-dev @types/mongoose

# Copie des scripts et fichiers DB
COPY scripts ./scripts
COPY .db ./.db
COPY . .

ENV NODE_ENV=development

CMD ["npx", "ts-node", "--project", "scripts/tsconfig.json", "scripts/migrate-data.ts"]
